spring:
  datasource:
      druid:
        driver-class-name: com.mysql.jdbc.Driver
        maxActive: 100
        initialSize: 50
        minIdle: 10
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: false
        filters: wall
mybatis-plus:
  mapper-locations: classpath*:**/mapper/xml/*Mapper.xml